version: 2
registries:
  oneobfuscator-git:
    type: git
    url: https://github.com/
    username: x-access-token
    password: ${{ secrets.DEPENDABOT_ONEOBFUSCATOR_PAT }}

updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[NuGet]"
      include: "scope"
    registries:
      - oneobfuscator-git

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[GitHub Actions]"
      include: "scope"
